### ISSUE TITLE
Suggestion: highlight changes in red and green

### ISSUE THREAD

**Issue by joeytwiddle** [shorterlife/challenge#2]
To make it easier for the viewer to see what code is changing...

### Suggestion 1

- At the start of each golf, highlight the text that is going to be removed in red (until/while that code is removed)

- Highlight the new text that has just been added in green (after/while that code is added)

![Screenshot_20200524_165040](https://user-images.githubusercontent.com/911799/82749986-adf4f080-9ddf-11ea-9498-c4e3accda4c6.png)

But I think this is difficult to implement, especially while we are in the middle of adding or removing a chunk of code.

### Suggestion 2

- Show two pre-wrap boxes: old code and new code, with red and green to highlight the changes, rather like we might see in a git diff

This would take more screen space, so perhaps only after the first reduction

**Comment by nbruno234** [comment]
Suggestion 1 is done, thanks for the feedback!
